rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-producer-8
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 2
    retry-times-when-send-failed: 2
    retry-next-server: true
